name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag jupyter-hub-executor:$(date +%s)

  publish:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        docker tag jupyter-hub-executor:$(date +%s) "${{ secrets.DOCKERHUB_USERNAME }}/jupyter-hub-executor:$(date +%s)"
        docker push "${{ secrets.DOCKERHUB_USERNAME }}/jupyter-hub-executor:$(date +%s)" 
